### ISSUE TITLE
レビュー src/AboutMe.js

### ISSUE THREAD

**Issue by superyusuke** [hashibadaiki/react-portfolio#10]
## relative import は使わない。absolute import を使う

以下の import 方法を relative import と言いますが、基本的にはこれは実務では使いません。

> import profile_picture from "./images/profile.jpg";

absolute import を使います。

以下の記事等を参考に、設定してみてください。

https://dev.to/mr_frontend/absolute-imports-in-create-react-app-3ge8

設定をして、以下のように import できるようにしてください。

```
import profile_picture from "src/images/profile.jpg";
```

**Comment by superyusuke** [comment]
> import profile_picture from "./images/profile.jpg";

snake case を使用しない。snake case とは blar_blar と `_` で繋ぐ手法です。

基本的に JS の世界では、理由がなければ camelCase を使用します。

ですからここでは profilePicture.jpg という名称にします。

**Comment by superyusuke** [comment]
https://github.com/hashibadaiki/react-portfolio/blob/d6ab657412cb510be513eed61d98bd5eb879cda5/src/AboutMe.js#L106

## <ul> 内全体について

ul は基本的に、内部にある li 要素が、同等の情報構造を持つ場合に使用する。

今回の各 li 要素は情報構造が全く異なるのでこれを ul でまとめるのは意味がない。（例えば画像があるところがあったりなかったり、p タグがあるところがあったりなかったり。）

ul, li ではなく普通に div でいい。

**Comment by superyusuke** [comment]
## インデントがおかしい

https://github.com/hashibadaiki/react-portfolio/blob/d6ab657412cb510be513eed61d98bd5eb879cda5/src/AboutMe.js#L70

おそらく prettier を使っていない。prettier をかならず実行するように。

**Comment by hashibadaiki** [comment]
これらに関する修正と付随する修正を実施しました。
